import LocalizedStrings from 'react-localization';

export const languageStrings = new LocalizedStrings({
  fr: {
    title: 'Title',
    subtitle: 'Subtitle',
    author: 'Author',
    year: 'Year',
    language: 'Language',
    youtuber: 'Youtuber',
    category: 'Category',
    contentType: 'Category',
    book: 'Book',
    books: 'Books',
    importantPage: 'Important page',
    video: 'Video',
    videos: 'Videos',
    quote: 'Quote',
    quotes: 'Quotes',
    popular: 'Popular',
    new: 'New',
    add: 'Add',
    settings: 'Settings',
    homepage: 'Homepage',
    bookmarks: 'Bookmarks',
    profile: 'Profile',
    timecode: "Video's timecode",
    validate: 'Validate',
    addContentStepperStep1: 'Choosing the category',
    addContentStepperStep2: 'Filling up the informations',
    addContentStepperStep3: 'Validating the creation',
    personalInfos: 'Personal Informations',
    fullName: 'Full name',
    username: 'Username',
    email: 'Email address',
    profileAddedContent: 'Added content',
  },
  en: {
    title: 'Titre',
    subtitle: 'Sous-titre',
    author: 'Auteur',
    year: 'Année',
    language: 'Langue',
    youtuber: 'Youtubeur',
    category: 'Genre',
    contentType: 'Categorie',
    book: 'Livre',
    books: 'Livres',
    importantPage: 'Page importante',
    video: 'Vidéo',
    videos: 'Vidéos',
    quote: 'Citation',
    quotes: 'Citations',
    popular: 'Populaires',
    new: 'Nouveaux',
    add: 'Ajouter',
    settings: 'Paramètres',
    homepage: 'Accueil',
    bookmarks: 'Favoris',
    profile: 'Profil',
    timecode: 'Timecode de la vidéo',
    validate: 'Valider',
    addContentStepperStep1: 'Choix de la catégorie',
    addContentStepperStep2: 'Remplir les informations',
    addContentStepperStep3: 'Valider la création',
    personalInfos: 'Informations personnelles',
    fullName: 'Nom complet',
    username: "Nom d'utilisateur",
    email: 'Addresse email',
    profileAddedContent: 'Contenu ajouté',
  },
});
