import Head from 'next/head';
import DefaultLayout from '@/layouts/DefaultLayout';
import { useState, useEffect } from 'react';
import GetBookmarkedContentAxios from '@/Axios/GetBookmarkedContentAxios';
import useAuth from '@/context/AuthContext';
import { useDispatch, useSelector } from 'react-redux';
import { ADD_BOOKMARKS } from '@/Redux/Reducers/BookmarksSlice';

export default function Favorites() {
  const [bookmarkContent, setBookmarkContent] = useState<any>(null);
  const { getUser }: any = useAuth();
  const user = getUser();
  const dispatch = useDispatch();
  const bookmarkRedux = useSelector((state: any) => state.bookmarks.bookmarks);

  useEffect(() => {
    if (user.id) {
      const fetchBookmarkContent = async () => {
        if (bookmarkRedux) {
          setBookmarkContent(bookmarkRedux);
        } else {
          const bookmarks = await GetBookmarkedContentAxios(user.id);
          setBookmarkContent(bookmarks);
          dispatch(ADD_BOOKMARKS(bookmarks));
        }
      };
      fetchBookmarkContent();
    }
  }, []);

  return (
    <>
      <Head>
        <title>Bookmarks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DefaultLayout>
          <div className="flex justify-center">
            <div className="flex-col mt-10">{bookmarkContent}</div>
          </div>
        </DefaultLayout>
      </main>
    </>
  );
}
