import Head from 'next/head';
import DefaultLayout from '@/layouts/DefaultLayout';
import { useState, useEffect } from 'react';
import FilterContentResponse from '@/Axios/FilterContentResponse';
import useContent from '@/context/ContentContext';

export default function Bookmarks() {
  const [bookmarkDisplay, setBookmarkDisplay] = useState<any>(null);
  const { contentData } = useContent();

  const noBookmarks = (
    <p className="mt-4 dark:text-white">
      Vous n'avez aucun favoris pour le moment.
    </p>
  );

  // Handling Bookmarks Loading, Display and NoContent
  useEffect(() => {
    if (contentData) {
      if (contentData.popularContent.length > 0) {
        const bookmarkedContents = contentData.popularContent.filter(
          (content: any) => content.isBookmarked != false
        );
        setBookmarkDisplay(FilterContentResponse(bookmarkedContents));
      } else {
        setBookmarkDisplay(noBookmarks);
      }
    } else {
      setBookmarkDisplay(<p className="mt-4 dark:text-white">Chargement...</p>);
    }
  }, [contentData]);

  return (
    <>
      <Head>
        <title>Bookmarks</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DefaultLayout>
          <div className="flex justify-center m-10 p-10">
            <div className="flex-col">
              {bookmarkDisplay && bookmarkDisplay.length > 0 && (
                <h1 className="mb-8 -mt-8 text-[1.1em] dark:text-white">
                  Mes favoris
                </h1>
              )}
              {bookmarkDisplay}
            </div>
          </div>
        </DefaultLayout>
      </main>
    </>
  );
}
