import Head from 'next/head';
import DefaultLayout from '@/layouts/DefaultLayout';

export default function Favorites() {
  return (
    <>
      <Head>
        <title>Favorites</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DefaultLayout>
          <h1>Favorites</h1>
        </DefaultLayout>
      </main>
    </>
  );
}
