import Head from 'next/head';
import DefaultLayout from '@/layouts/DefaultLayout';
import { useSelector } from 'react-redux';
import { ReduxUserType } from '@/Types/ReduxUserType';

export default function Home() {
  // const userData = useSelector((state: ReduxUserType) => state.user.user);
  return (
    <>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DefaultLayout>
          <>
            <h1>Homepage</h1>
          </>
        </DefaultLayout>
      </main>
    </>
  );
}
