import Head from 'next/head';
import DefaultLayout from '@/layouts/DefaultLayout';
import BookCard from '@/components/BookCard';
import image from '../public/images/book-cover-platon.jpg';

export default function Home() {
  return (
    <>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gray-200">
        <DefaultLayout>
          <div className="flex justify-center">
            <div className="flex-col">
              <h1 className="mb-24">Homepage</h1>
              <BookCard bookCoverUrl={image} />
            </div>
          </div>
        </DefaultLayout>
      </main>
    </>
  );
}
