import Head from 'next/head';
import DefaultLayout from '@/layouts/DefaultLayout';
import ProfileMenu from '@/components/ProfileMenu';
import useAuth from '@/context/AuthContext';
import { useEffect, useState } from 'react';
import { userType } from '@/Types/UserType';
import useLang from '@/hooks/useLang';
import useContent from '@/context/ContentContext';
import FilterContentResponse from '@/Axios/FilterContentResponse';

export default function Profile() {
  const { getUser }: any = useAuth();
  const [userData, setUserData] = useState<userType | null>(null);
  const langStrings = useLang();
  const { contentData } = useContent();
  const [userContents, setUserContents] = useState<any>();

  useEffect(() => {
    setUserData(getUser());
  }, []);

  useEffect(() => {
    if (contentData && userData) {
      if (contentData.popularContent.length > 0 && userData.id) {
        const userFilteredContent = FilterContentResponse(
          contentData.popularContent.filter(
            (content: any) => content.user_id === userData.id
          )
        );
        setUserContents(userFilteredContent);
      }
    }
  }, [contentData, userData]);

  return (
    <>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="[100vh]">
        <DefaultLayout>
          <div className="flex justify-center 2xl:mr-[50px] mt-8">
            <div className="h-full bg-gray-300 dark:bg-gray-800 dark:border dark:border-gray-700 md:p-8 flex-col lg:w-[80vw] lg:max-w-[1330px] w-[100vw]">
              <div className="bg-white rounded-lg shadow-xl pb-8">
                <div className="w-full h-[250px]">
                  <img
                    src="https://vojislavd.com/ta-template-demo/assets/img/profile-background.jpg"
                    className="w-full h-full rounded-tl-lg rounded-tr-lg"
                  />
                </div>
                <div className="flex flex-col items-center -mt-20">
                  <img
                    src="https://vojislavd.com/ta-template-demo/assets/img/profile.jpg"
                    className="lg:w-40 w-32 border-4 border-white rounded-full"
                  />
                  <div className="flex items-center space-x-2 mt-2">
                    <p className="text-2xl">{userData?.name}</p>
                  </div>
                  <p className="text-sm text-gray-500">{userData?.username}</p>
                </div>
                <div className="flex-1 flex flex-col items-center lg:items-end justify-end px-8 mt-2">
                  <div className="flex items-center space-x-4 mt-2">
                    <ProfileMenu />
                  </div>
                </div>
              </div>

              <div className="w-full">
                <div className="my-4 flex flex-col 2xl:flex-row lg:min-w-[40%]">
                  <div className="lg:min-w-[100%] flex-col 2xl:w-1/3">
                    <div className="flex-1 bg-white rounded-lg shadow-xl p-8">
                      <h4 className="text-xl text-gray-900 font-bold pb-3">
                        {langStrings && langStrings.personalInfos}
                      </h4>
                      <ul className="mt-2 text-gray-700 text-[0.7em] md:text-base">
                        <li className="flex border-y py-2">
                          <span className="font-bold w-40">
                            {langStrings && langStrings.fullName}:
                          </span>
                          <span>{userData?.name}</span>
                        </li>
                        <li className="flex border-y py-2">
                          <span className="font-bold w-40">
                            {langStrings && langStrings.username}:
                          </span>
                          <span>{userData?.username}</span>
                        </li>
                        <li className="flex border-b py-2">
                          <span className="font-bold w-40">
                            {langStrings && langStrings.email}:
                          </span>
                          <span>{userData?.email}</span>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>

                <div className="my-4 flex flex-col w-full justify-center 2xl:flex-row space-y-4 2xl:space-y-0 2xl:space-x-4 lg:min-w-[58%]">
                  <div className="lg:min-w-full flex flex-col 2xl:w-1/3 lg:min-h-full">
                    <div className="flex-1 bg-white rounded-lg shadow-xl p-8">
                      <h4 className="text-xl text-gray-900 font-bold pb-3 mb-14">
                        {langStrings && langStrings.profileAddedContent}
                      </h4>
                      <div className="flex justify-center">
                        <div className="flex flex-col">
                          {userContents && userContents}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </DefaultLayout>
      </main>
    </>
  );
}
