import React, { useEffect, useState } from 'react';
import { languageStrings } from '@/utils/languageStrings';
import Head from 'next/head';
import useAuth from '@/context/AuthContext';

export default function ProfileContent() {
  const [langStrings, setLangStrings] = useState<any>(null);
  const { getUser } = useAuth();
  const user = getUser();

  useEffect(() => {
    setLangStrings(languageStrings);
  }, [languageStrings]);

  const handleInputChange = (e: any) => {};
  const handleSubmit = (e: any) => {};

  return (
    <>
      <Head>
        <title>{langStrings && langStrings.settings}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <div className="flex flex-col md:h-screen lg:py-0">
          <h1 className="mb-6 text-xl font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
            {langStrings && langStrings.myProfile}
          </h1>
          <form
            className="space-y-4 md:space-y-6"
            action="#"
            onSubmit={(e) => handleSubmit(e)}
          >
            <div>
              <label
                htmlFor="name"
                className="block mb-1 text-sm font-medium text-gray-900 dark:text-white"
              >
                Nom complet
              </label>
              <input
                onChange={(e) => handleInputChange(e)}
                type="text"
                name="name"
                id="name"
                value={user && user.name}
                className="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              />
            </div>
            <div></div>
            <div>
              <label
                htmlFor="email"
                className="block mb-1 text-sm font-medium text-gray-900 dark:text-white"
              >
                Email
              </label>
              <input
                onChange={(e) => handleInputChange(e)}
                type="email"
                name="email"
                id="email"
                className="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                value={user && user.email}
              />
            </div>
            <div>
              <label
                htmlFor="username"
                className="block mb-1 text-sm font-medium text-gray-900 dark:text-white"
              >
                Nom d'utilisateur
              </label>
              <input
                onChange={(e) => handleInputChange(e)}
                type="text"
                name="username"
                id="username"
                value={user && user.username}
                className="bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
              />
            </div>
            <button
              type="submit"
              className="w-full text-white bg-primary-600 hover:bg-primary-700 focus:ring-4 focus:outline-none focus:ring-primary-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-primary-600 dark:hover:bg-primary-700 dark:focus:ring-primary-800"
            >
              Enregistrer
            </button>
          </form>
        </div>
      </section>
    </>
  );
}
